[build]
  cmd = "go build -o main main.go"
  bin = "main"
  dir = "."
  poll = true
  include_ext = ["go"]
  exclude_dir = ["vendor"]
  run_after_build = "chmod +x main"
  tmp_dir = "air"
[log]
  level = "debug"